### ISSUE TITLE
iPhone 14模拟器启动报错，这个包sdk支持还支持最新的iPhone吗

### ISSUE THREAD

**Issue by fuxianwei** [netease-im/NERTC-Flutter-SDK#16]
flutter doctor信息：
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.1 22C65 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

iPhone14启动报错：
Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/admin/Desktop/work/workspace/chat/nim-uikit-flutter-main/im_app/ios/Pods/NERtcSDK/NERTC/NERtcSDK/NMCBasicModuleFramework.framework/NMCBasicModuleFramework' for architecture arm64

Could not build the application for the simulator.
Error launching application on iPhone 14.

**Comment by chandarlee** [comment]
> flutter doctor信息： Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.7.6, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) [✓] Xcode - develop for iOS and macOS (Xcode 14.2) [✓] Chrome - develop for the web [✓] Android Studio (version 2022.1) [✓] VS Code (version 1.76.0) [✓] Connected device (3 available) [✓] HTTP Host Availability
> 
> • No issues found!
> 
> iPhone14启动报错： Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/admin/Desktop/work/workspace/chat/nim-uikit-flutter-main/im_app/ios/Pods/NERtcSDK/NERTC/NERtcSDK/NMCBasicModuleFramework.framework/NMCBasicModuleFramework' for architecture arm64
> 
> Could not build the application for the simulator. Error launching application on iPhone 14.

请问你们依赖的是哪个版本？

**Comment by chandarlee** [comment]
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        **config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"**
    end
  end
end

需要修改podfile文件，添加配置：config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

**Comment by fuxianwei** [comment]
依赖的nertc: ^4.6.0-rc.0最新版，可以安装了，感谢！请问下这个sdk大概什么时候会更新，适配最新的flutter和系统了

**Comment by chandarlee** [comment]
预计4月份会更新版本；Flutter新版本的适配不需要额外的工作，本身就是支持的

**Comment by fuxianwei** [comment]
> 预计4月份会更新版本；Flutter新版本的适配不需要额外的工作，本身就是支持的

好的，期待新版本尽快发布
