### ISSUE TITLE
期待尽快发布稳定版本

### ISSUE THREAD

**Issue by luohs** [netease-im/NERTC-Flutter-SDK#5]
望眼欲穿，期待尽快发布稳定版本

**Comment by FreeSunny** [comment]
> 望眼欲穿，期待尽快发布稳定版本

release 分支之后就是稳定版本

**Comment by liuqijun** [comment]
目前稳定版本为 0.3.7+2, 对应原生平台版本为 SDK v3.7.1.     https://pub.dev/packages/nertc
