### ISSUE TITLE
iOS 报错

### ISSUE THREAD

**Issue by NieYinlong** [netease-im/NERTC-Flutter-SDK#7]
![image](https://user-images.githubusercontent.com/15773477/100208823-1b770a80-2f44-11eb-938f-eccd7ba264bd.png)

**Comment by FreeSunny** [comment]
can you provider mobile os version?

**Comment by FreeSunny** [comment]
11.4.1 not crash！

**Comment by liuqijun** [comment]
iPhone 7 测试没有重现问题，后续有问题再进一步分析
